{
  pkgs,
  config,
  inputs,
  lib,
  ...
}:
let
  # L235 - THE FLEET GATE, as four hooks of this repository's own (D-115).
  #
  # WHY A REPOSITORY THAT ALREADY HAS A GATE STILL NEEDS THESE. This repository
  # sets a LOCAL `core.hooksPath` before the installer runs (the task below), so
  # it was never one of the eight that prek refused - it declares its own hooks
  # and they work. The lane's cut baton said to leave it alone for exactly that
  # reason, and verify round 2 measured why that was not enough:
  #
  #   this repository declares no `gitleaks`.
  #
  # It reaches the fleet's gitleaks TODAY, and only by accident of state: the
  # local value is written by a devenv task, so before the first shell entry git
  # resolves the fleet's GLOBAL `core.hooksPath` and runs the whole fleet gate
  # here. L235 removes that global value. Without these entries this repository
  # would keep its own hooks and quietly lose the one scanner that fires on a
  # credential this machine has never seen - which is the leak worth stopping,
  # since it is usually pasted in from elsewhere.
  #
  # So the four entries are additive: this repository's own hooks still run,
  # and the fleet gate runs beside them. That is the same shape L173 gave the
  # flake and `claude-src`, both of which also own their gate.
  #
  # Built through writeShellApplication so the script is shellchecked at build
  # time and the entries name a store path rather than a working-tree file.
  fleetGateHook = "${
    pkgs.writeShellApplication {
      name = "fleet-gate-hook";
      runtimeInputs = [
        pkgs.coreutils
        pkgs.git
      ];
      text = builtins.readFile ./hooks/fleet-gate-hook;
    }
  }/bin/fleet-gate-hook";
in
{

  # Environment variables
  dotenv = {
    enable = true;
    filename = [ ".env" ];
  };

  difftastic.enable = true;

  # Rust language support
  languages.rust = {
    enable = true;
    channel = "nightly";

    # Rust components
    components = [
      "rustc"
      "cargo"
      "clippy"
      "rustfmt"
      "rust-analyzer"
      "rust-src"
      "rust-std"
      "llvm-tools-preview"
    ];

    # Targets for cross-compilation
    targets = [ "x86_64-unknown-linux-gnu" ];
  };

  # Development packages
  packages = with pkgs; [
    # Rust development tools
    cargo-edit # cargo add, cargo rm, cargo upgrade
    cargo-watch # cargo watch for auto-rebuild
    cargo-expand # cargo expand for macro debugging
    cargo-outdated # check for outdated dependencies
    cargo-audit # security audit
    cargo-deny # dependency management
    cargo-release # release management
    cargo-cross # cross-compilation
    cargo-nextest # next-generation test runner
    cargo-llvm-cov # code coverage
    cargo-machete # find unused dependencies
    cargo-update # update installed binaries
    bacon

    # Build tools and linkers
    gcc
    binutils
    pkg-config
    openssl

    # Development utilities
    git
    jq
    tree
    curl
    gh
    glab

    # Container tools
    docker
    docker-compose
  ];

  # Git hooks
  # Exclude machine-owned / non-prose files from all hooks so lint stays green
  # and we don't churn generated content:
  #   - docs/feature/**   transient nWave scratch, regenerated each wave
  #   - CHANGELOG.md       generated by the release changelog action
  #   - tests/fixtures/**  parser test data (bare URLs etc. are intentional)
  git-hooks.excludes = [
    "^docs/feature/"
    "^CHANGELOG\\.md$"
    "^tests/fixtures/"
  ];

  git-hooks.hooks = {
    # L235 - the fleet gate, reached as four of this repo's own hooks. The
    # rationale is in the `let` block at the top of this file; what matters here
    # is that these four are ordinary entries with nothing special about them.
    fleet-gate = {
      enable = true;
      name = "fleet gate";
      stages = [ "pre-commit" ];
      entry = "${fleetGateHook} pre-commit";
      language = "system";
      pass_filenames = false;
      always_run = true;
    };

    # pass_filenames, because git hands commit-msg the message file and the
    # fleet gate's gitlint and commitizen read it. Getting this wrong lints the
    # wrong thing while still exiting 0.
    fleet-gate-commit-msg = {
      enable = true;
      name = "fleet gate (message)";
      stages = [ "commit-msg" ];
      entry = "${fleetGateHook} commit-msg";
      language = "system";
      pass_filenames = true;
      always_run = true;
    };

    fleet-gate-pre-push = {
      enable = true;
      name = "fleet gate (push)";
      stages = [ "pre-push" ];
      entry = "${fleetGateHook} pre-push";
      language = "system";
      pass_filenames = false;
      always_run = true;
    };

    # The commit diary is hooks_everywhere.nix's post-commit hook - NOT
    # pkgs/git-commit-gate, which ships pre-commit and commit-msg only. On a box
    # with no fleet gate there is no diary, and the entry says so per commit.
    fleet-gate-post-commit = {
      enable = true;
      name = "fleet gate (diary)";
      stages = [ "post-commit" ];
      entry = "${fleetGateHook} post-commit";
      language = "system";
      pass_filenames = false;
      always_run = true;
    };

    rusty-commit-saver = {
      enable = true;
      name = "🦀 Rusty Commit Saver";
      stages = [ "post-commit" ];
      after = [
        "commitizen"
        "gitlint"
      ];
      entry = "${inputs.rusty-commit-saver.packages.${pkgs.system}.default}/bin/rusty-commit-saver";
      pass_filenames = false;
      language = "system";
      always_run = true;
    };

    check-merge-conflicts = {
      name = "🔒 Check Merge Conflicts";
      enable = true;
      stages = [ "pre-commit" ];
    };

    detect-aws-credentials = {
      name = "💭 Detect AWS Credentials";
      enable = true;
      stages = [ "pre-commit" ];
    };

    detect-private-keys = {
      name = "🔑 Detect Private Keys";
      enable = true;
      stages = [ "pre-commit" ];
    };

    end-of-file-fixer = {
      name = "🔚 End of File Fixer";
      enable = true;
      stages = [ "pre-commit" ];
      # YAML trailing-newline is owned by treefmt/yamlfmt (which keeps a final
      # blank line); excluding YAML here avoids the two hooks fighting over it.
      excludes = [
        "^docs/feature/"
        "\\.ya?ml$"
      ];
    };

    mixed-line-endings = {
      name = "🔀 Mixed Line Endings";
      enable = true;
      stages = [ "pre-commit" ];
    };

    trim-trailing-whitespace = {
      name = "✨ Trim Trailing Whitespace";
      enable = true;
      stages = [ "pre-commit" ];
    };

    shellcheck = {
      name = "✨ Shell Check";
      enable = true;
      stages = [ "pre-commit" ];
    };

    mdsh = {
      enable = true;
      name = "✨ MDSH";
      stages = [ "pre-commit" ];
    };

    treefmt = {
      name = "🌲 TreeFMT";
      enable = true;
      settings.formatters = [
        pkgs.nixfmt
        pkgs.deadnix
        pkgs.yamlfmt
        pkgs.rustfmt
        pkgs.toml-sort
      ];
      stages = [ "pre-commit" ];
    };

    commitizen = {
      name = "✨ Commitizen";
      enable = true;
      stages = [ "post-commit" ];
    };

    gitlint = {
      name = "✨ GitLint";
      enable = true;
    };

    markdownlint = {
      name = "✨ MarkdownLint";
      enable = true;
      stages = [ "pre-commit" ];
      settings.configuration = {
        MD033 = false;
        MD013 = {
          line_length = 120;
          tables = false;
          code_blocks = false;
        };
        MD041 = false;
        MD060 = false;
      };
    };

    # Rust-specific hooks
    clippy = {
      name = "🦀 Clippy";
      enable = true;
      stages = [ "pre-commit" ];
    };
  };

  # Development scripts
  scripts = {
    hello = {
      description = "Welcome message for Rust project";
      exec = ''
        figlet -w 1000 "rusty-commit-lister"
        echo "🦀 Welcome to your Rust development environment!"
        echo "   Project: rusty-commit-lister"
        echo "   Crate: rusty_commit_lister"
        echo ""
        echo "🔧 Rust toolchain information:"
        rustc --version
        cargo --version
        echo ""
      '';
    };

    prepare_git_repo = {
      description = "One time script to bootstrap the github/gitlab repository";
      exec = ''
        #!/usr/bin/env bash
        set -euo pipefail

        if git rev-parse --git-dir > /dev/null 2>&1 && git remote get-url origin > /dev/null 2>&1; then
            echo "Repository with remote origin exists"
        else
            echo "Not a repository or no remote configured"

            if [[ "$PWD" == *"github.com"* ]]; then
              echo "Current directory contains github.com"
              gh repo new "rusty-commit-lister" --public
            elif [[ "$PWD" == *"gitlab.com"* ]]; then
              echo "Current directory contains gitlab.com"
              glab repo create --name "rusty-commit-lister"
            else
              echo "Current directory is niether github or gitlab, manual operation is needed"
            fi
        fi
      '';
    };

    build = {
      description = "Build the Rust project";
      exec = ''
        #!/usr/bin/env bash
        set -euo pipefail
        echo "🔨 Building Rust project..."
        cargo build
      '';
    };

    build-release = {
      description = "Build the Rust project in release mode";
      exec = ''
        #!/usr/bin/env bash
        set -euo pipefail
        echo "🚀 Building Rust project (release mode)..."
        cargo build --release
      '';
    };

    # Named `test-all`, never `test`: in the devenv shell the bash builtin
    # `test` wins the name lookup, so a script called `test` silently runs the
    # builtin with no arguments and exits 1 without running the suite.
    test-all = {
      description = "Run tests with cargo nextest";
      exec = ''
        #!/usr/bin/env bash
        set -euo pipefail
        echo "🧪 Running tests..."
        cargo nextest run --no-fail-fast --all-targets
      '';
    };

    test-coverage = {
      description = "Run tests with coverage";
      exec = ''
        #!/usr/bin/env bash
        set -euo pipefail
        echo "📊 Running tests with coverage..."
        cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
        cargo llvm-cov report
      '';
    };

    format = {
      description = "Format code with rustfmt";
      exec = ''
        #!/usr/bin/env bash
        set -euo pipefail
        echo "🎨 Formatting code..."
        cargo fmt
      '';
    };

    check = {
      description = "Check code without building";
      exec = ''
        #!/usr/bin/env bash
        set -euo pipefail
        echo "✅ Checking code..."
        cargo check
      '';
    };

    audit = {
      description = "Security audit with cargo audit";
      exec = ''
        #!/usr/bin/env bash
        set -euo pipefail
        echo "🔒 Running security audit..."
        cargo audit
      '';
    };

    outdated = {
      description = "Check for outdated dependencies";
      exec = ''
        #!/usr/bin/env bash
        set -euo pipefail
        echo "📦 Checking for outdated dependencies..."
        cargo outdated
      '';
    };

    watch = {
      description = "Watch for changes and rebuild";
      exec = ''
        #!/usr/bin/env bash
        set -euo pipefail
        echo "👀 Watching for changes..."
        cargo watch -x build
      '';
    };

    watch-clippy = {
      description = "Watch and re-run tests on file changes";
      exec = ''
        bacon clippy
      '';
    };

    watch-coverage = {
      description = "Watch and re-run nextest on file changes";
      exec = ''
        bacon coverage
      '';
    };

    run = {
      description = "Run the binary";
      exec = ''
        #!/usr/bin/env bash
        set -euo pipefail
        echo "🚀 Running rusty-commit-lister..."
        cargo run
      '';
    };

    clean = {
      description = "Clean build artifacts";
      exec = ''
        #!/usr/bin/env bash
        set -euo pipefail
        echo "🧹 Cleaning build artifacts..."
        cargo clean
      '';
    };

    deps = {
      description = "Show dependency tree";
      exec = ''
        #!/usr/bin/env bash
        set -euo pipefail
        echo "📦 Dependency tree:"
        cargo tree
      '';
    };

    devhelp = {
      description = "Returns the helper commands";
      exec = ''
        echo
        echo 💡 Helper scripts for Rust development:
        echo
        ${pkgs.gnused}/bin/sed -e 's| |••|g' -e 's|=| |' <<EOF | ${pkgs.util-linuxMinimal}/bin/column -t | ${pkgs.gnused}/bin/sed -e 's|^|• |' -e 's|••| |g'
        ${lib.generators.toKeyValue { } (lib.mapAttrs (_name: value: value.description) config.scripts)}
        EOF
        echo
      '';
    };
  };

  # Enter shell configuration
  enterShell = ''
    if [ -f ".env" ]; then
      eval "$(<.env)"
    fi

    # Durable repo-local git hooks: a global core.hooksPath (e.g. ~/.config/git/hooks)
    # otherwise shadows the devenv/prek-installed hooks in this repo. Re-assert the
    # repo-local override on every shell entry so it self-heals after a fresh clone.
    if git rev-parse --git-dir > /dev/null 2>&1; then
      git config --local core.hooksPath "$(git rev-parse --absolute-git-dir)/hooks"
    fi

    # Set environment variables for Rust development
    export GREET="rusty-commit-lister"
    export RUST_LOG="info"
    export RUST_BACKTRACE="1"

    # Convenient aliases
    alias c=check
    alias b=build
    alias br=build-release
    alias t=test-all
    alias tc=test-coverage
    alias l=lint
    alias f=format
    alias r=run
    alias w=watch-coverage
    alias wcc=watch-clippy
    alias wt=watch-test

    # Welcome message
    hello

    # `devhelp` is the only renderer of the script table. Inlining a second
    # copy here is what let the two drift, and the copy in `devhelp` still
    # carried the bootstrap template's title instead of this repo's.
    devhelp
  '';

  enterTest = ''
    cargo clippy --all-targets -- -D warnings
    cargo llvm-cov --html nextest --no-fail-fast
    cargo nextest run --no-fail-fast --all-targets
  '';
}
